# Generated by Django 4.2 on 2023-05-10 01:50

from django.db import migrations, models
import django.db.models.deletion
import utils.utils_time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UsersApp', '0004_followrelation_remove_user_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('search_for', models.TextField(default=str, max_length=3000)),
                ('search_time', models.FloatField(default=utils.utils_time.get_timestamp)),
                ('deleted', models.BooleanField(default=False)),
                ('search_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.user')),
            ],
        ),
        migrations.AddIndex(
            model_name='searchmodel',
            index=models.Index(fields=['search_user'], name='SearchApp_s_search__2919e6_idx'),
        ),
    ]
