# Generated by Django 4.1 on 2023-05-20 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0005_user_last_view_folllowing_moment'),
        ('SearchApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchmodel',
            name='search_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_records', to='UsersApp.user'),
        ),
    ]
