# Generated by Django 4.1.7 on 2023-03-31 08:51

from django.db import migrations, models
import utils.utils_time


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GIFImage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("hash", models.CharField(max_length=255, unique=True)),
                ("uploader", models.CharField(max_length=255)),
                (
                    "upload_time",
                    models.FloatField(default=utils.utils_time.get_timestamp),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="gifimage",
            index=models.Index(fields=["id"], name="ImagesApp_g_id_0b4686_idx"),
        ),
    ]
