# Generated by Django 4.1 on 2023-04-10 15:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImagesApp', '0003_rename_imageuploadrecord_gifimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifimage',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gifimage',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
        migrations.AddField(
            model_name='gifimage',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AddField(
            model_name='gifimage',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
