# Generated by Django 4.1 on 2023-04-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImagesApp', '0004_gifimage_height_gifimage_tags_gifimage_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifimage',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gifimage',
            name='width',
            field=models.IntegerField(),
        ),
    ]
