# Generated by Django 4.1 on 2023-04-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImagesApp', '0005_alter_gifimage_height_alter_gifimage_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifimage',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=255),
        ),
        migrations.AddField(
            model_name='gifimage',
            name='description',
            field=models.TextField(default='', max_length=3000),
        ),
    ]
