# Generated by Django 4.1 on 2023-04-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImagesApp', '0007_comment_comment_imagesapp_c_id_644bad_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gifimagecounter',
            name='ImagesApp_g_id_367fb9_idx',
        ),
        migrations.AddIndex(
            model_name='gifimage',
            index=models.Index(fields=['hash'], name='ImagesApp_g_hash_95f45a_idx'),
        ),
        migrations.AddIndex(
            model_name='gifimagecounter',
            index=models.Index(fields=['hash'], name='ImagesApp_g_hash_b54911_idx'),
        ),
    ]
