# Generated by Django 4.1 on 2023-04-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImagesApp', '0009_rename_text_comment_content_comment_reply_to_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
