# Generated by Django 4.1 on 2023-04-13 16:30

import django.contrib.postgres.fields
from django.db import migrations, models
import utils.utils_time


class Migration(migrations.Migration):

    dependencies = [
        ('ImagesApp', '0011_alter_gifimagecounter_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='AronaImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=255)),
                ('uploader', models.CharField(max_length=255)),
                ('upload_time', models.FloatField(default=utils.utils_time.get_timestamp)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('title', models.CharField(default='Untitled', max_length=255)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('description', models.TextField(default=str, max_length=3000)),
                ('category', models.CharField(default='Uncategorized', max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='GIFImageCounter',
            new_name='AronaImageCounter',
        ),
        migrations.DeleteModel(
            name='GIFImage',
        ),
        migrations.RenameIndex(
            model_name='aronaimagecounter',
            new_name='ImagesApp_a_hash_87c978_idx',
            old_name='ImagesApp_g_hash_b54911_idx',
        ),
        migrations.AddIndex(
            model_name='aronaimage',
            index=models.Index(fields=['id'], name='ImagesApp_a_id_e9bf25_idx'),
        ),
        migrations.AddIndex(
            model_name='aronaimage',
            index=models.Index(fields=['hash'], name='ImagesApp_a_hash_baabee_idx'),
        ),
    ]
