# Generated by Django 4.1 on 2023-04-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImagesApp', '0012_aronaimage_rename_gifimagecounter_aronaimagecounter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aronaimage',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aronaimage',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
