# Generated by Django 4.1 on 2023-05-15 15:15

from django.db import migrations, models
import django.db.models.deletion
import utils.utils_time


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0004_followrelation_remove_user_followers'),
        ('ImagesApp', '0014_delete_aronaimagecounter_alter_aronaimage_uploader'),
    ]

    operations = [
        migrations.CreateModel(
            name='AronaImageBrowseRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('browse_time', models.FloatField(default=utils.utils_time.get_timestamp)),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.user')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImagesApp.aronaimage')),
            ],
        ),
        migrations.AddIndex(
            model_name='aronaimagebrowserecord',
            index=models.Index(fields=['id'], name='ImagesApp_a_id_226a24_idx'),
        ),
        migrations.AddIndex(
            model_name='aronaimagebrowserecord',
            index=models.Index(fields=['image'], name='ImagesApp_a_image_i_37842d_idx'),
        ),
        migrations.AddIndex(
            model_name='aronaimagebrowserecord',
            index=models.Index(fields=['browser'], name='ImagesApp_a_browser_5fd75d_idx'),
        ),
    ]
