# Generated by Django 4.1 on 2023-05-19 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImagesApp', '0015_aronaimagebrowserecord_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='aronaimagebrowserecord',
            name='ImagesApp_a_image_i_37842d_idx',
        ),
    ]
