# Generated by Django 4.1 on 2023-05-19 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0004_followrelation_remove_user_followers'),
        ('ImagesApp', '0016_remove_aronaimagebrowserecord_imagesapp_a_image_i_37842d_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUtilRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('result_url', models.CharField(max_length=255)),
                ('util_type', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.user')),
            ],
        ),
        migrations.AddIndex(
            model_name='imageutilrecord',
            index=models.Index(fields=['id'], name='ImagesApp_i_id_9b166c_idx'),
        ),
        migrations.AddIndex(
            model_name='imageutilrecord',
            index=models.Index(fields=['user'], name='ImagesApp_i_user_id_7578d6_idx'),
        ),
    ]
