# Generated by Django 4.1 on 2023-05-19 10:20

from django.db import migrations, models
import utils.utils_time


class Migration(migrations.Migration):

    dependencies = [
        ('ImagesApp', '0017_imageutilrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageutilrecord',
            name='util_time',
            field=models.FloatField(default=utils.utils_time.get_timestamp),
        ),
    ]
