# Generated by Django 4.1 on 2023-05-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImagesApp', '0019_alter_imageutilrecord_result_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageutilrecord',
            old_name='util_time',
            new_name='finish_time',
        ),
        migrations.AddField(
            model_name='imageutilrecord',
            name='expiry',
            field=models.FloatField(default=604800.0),
        ),
        migrations.AddField(
            model_name='imageutilrecord',
            name='result_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
