# Generated by Django 4.1 on 2023-05-20 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0005_user_last_view_folllowing_moment'),
        ('ImagesApp', '0021_alter_imageutilrecord_result_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aronaimage',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='UsersApp.user'),
        ),
        migrations.AlterField(
            model_name='aronaimagebrowserecord',
            name='browser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browse_records', to='UsersApp.user'),
        ),
        migrations.AlterField(
            model_name='imageutilrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='util_records', to='UsersApp.user'),
        ),
    ]
