# Generated by Django 4.1.7 on 2023-03-31 08:51

from django.db import migrations, models
import utils.utils_time


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(default="", max_length=255)),
                ("email", models.CharField(default="", max_length=255)),
                ("salt", models.CharField(default="", max_length=255)),
                ("nickname", models.CharField(default="", max_length=255)),
                (
                    "registerTime",
                    models.FloatField(default=utils.utils_time.get_timestamp),
                ),
                ("userType", models.CharField(default="user", max_length=255)),
                ("slogan", models.CharField(default="114514", max_length=255)),
                ("followingCount", models.IntegerField(default=0)),
                ("followerCount", models.IntegerField(default=0)),
                ("uploadCount", models.IntegerField(default=0)),
                ("followers", models.ManyToManyField(to="UsersApp.user")),
            ],
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["username"], name="UsersApp_us_usernam_a8630e_idx"
            ),
        ),
    ]
