# Generated by Django 4.1 on 2023-04-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0002_user_mail_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mail_code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
