# Generated by Django 4.1.3 on 2023-04-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0003_alter_user_mail_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(default='', max_length=255)),
                ('following', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
