# Generated by Django 4.2 on 2023-05-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0004_followrelation_remove_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_view_folllowing_moment',
            field=models.FloatField(default=0.0),
        ),
    ]
