# Generated by Django 4.1.3 on 2023-05-14 22:54

from django.db import migrations, models
import django.db.models.deletion
import utils.utils_time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UsersApp', '0004_followrelation_remove_user_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.FloatField(default=utils.utils_time.get_timestamp)),
                ('content', models.CharField(default='', max_length=3000)),
                ('deleted', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='UsersApp.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='UsersApp.user')),
            ],
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['id'], name='MessageApp__id_005c79_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='MessageApp__sender__531d30_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver'], name='MessageApp__receive_e32bcc_idx'),
        ),
    ]
