# Generated by Django 4.1 on 2023-04-12 16:36

import django.contrib.postgres.fields
from django.db import migrations, models
import utils.utils_time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=3000)),
                ('poster', models.CharField(max_length=255)),
                ('post_time', models.FloatField(default=utils.utils_time.get_timestamp)),
                ('likes', models.IntegerField(default=0)),
                ('reply_to_image_id', models.BigIntegerField()),
                ('reply_to_comment_id', models.BigIntegerField(default=None)),
                ('reply_to_user', models.CharField(default=None, max_length=255)),
                ('replies', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, size=None)),
            ],
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['id'], name='SocialApp_c_id_bd7795_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['reply_to_image_id'], name='SocialApp_c_reply_t_7851ac_idx'),
        ),
    ]
