# Generated by Django 4.1 on 2023-04-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_to_comment_id',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_to_user',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
