# Generated by Django 4.1 on 2023-04-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0002_alter_comment_reply_to_comment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeCommentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('comment_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LikeImageRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('image_id', models.BigIntegerField()),
            ],
        ),
        migrations.AddIndex(
            model_name='likeimagerelation',
            index=models.Index(fields=['username'], name='SocialApp_l_usernam_b76e51_idx'),
        ),
        migrations.AddIndex(
            model_name='likeimagerelation',
            index=models.Index(fields=['image_id'], name='SocialApp_l_image_i_a8fd35_idx'),
        ),
        migrations.AddIndex(
            model_name='likecommentrelation',
            index=models.Index(fields=['username'], name='SocialApp_l_usernam_1957b7_idx'),
        ),
        migrations.AddIndex(
            model_name='likecommentrelation',
            index=models.Index(fields=['comment_id'], name='SocialApp_l_comment_5d0ffe_idx'),
        ),
    ]
