# Generated by Django 4.1 on 2023-04-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0004_comment_comments'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='SocialApp_c_reply_t_7851ac_idx',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='reply_to_image_id',
            new_name='belong_to_image_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='replies',
        ),
        migrations.AddField(
            model_name='comment',
            name='belong_to_comment_id',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['belong_to_image_id'], name='SocialApp_c_belong__1223de_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['belong_to_comment_id'], name='SocialApp_c_belong__95f1ab_idx'),
        ),
    ]
