# Generated by Django 4.1 on 2023-04-18 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImagesApp', '0014_delete_aronaimagecounter_alter_aronaimage_uploader'),
        ('UsersApp', '0004_followrelation_remove_user_followers'),
        ('SocialApp', '0005_remove_comment_socialapp_c_reply_t_7851ac_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='likecommentrelation',
            name='SocialApp_l_usernam_1957b7_idx',
        ),
        migrations.RemoveIndex(
            model_name='likecommentrelation',
            name='SocialApp_l_comment_5d0ffe_idx',
        ),
        migrations.RemoveIndex(
            model_name='likeimagerelation',
            name='SocialApp_l_usernam_b76e51_idx',
        ),
        migrations.RemoveIndex(
            model_name='likeimagerelation',
            name='SocialApp_l_image_i_a8fd35_idx',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='belong_to_comment_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='belong_to_image_id',
        ),
        migrations.RemoveField(
            model_name='likecommentrelation',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='likecommentrelation',
            name='username',
        ),
        migrations.RemoveField(
            model_name='likeimagerelation',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='likeimagerelation',
            name='username',
        ),
        migrations.AddField(
            model_name='comment',
            name='belong_to_comment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialApp.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='belong_to_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ImagesApp.aronaimage'),
        ),
        migrations.AddField(
            model_name='likecommentrelation',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialApp.comment'),
        ),
        migrations.AddField(
            model_name='likecommentrelation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UsersApp.user'),
        ),
        migrations.AddField(
            model_name='likeimagerelation',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ImagesApp.aronaimage'),
        ),
        migrations.AddField(
            model_name='likeimagerelation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UsersApp.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.user'),
        ),
        migrations.AddIndex(
            model_name='likecommentrelation',
            index=models.Index(fields=['user'], name='SocialApp_l_user_id_290ba5_idx'),
        ),
        migrations.AddIndex(
            model_name='likecommentrelation',
            index=models.Index(fields=['comment'], name='SocialApp_l_comment_5d0ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='likeimagerelation',
            index=models.Index(fields=['user'], name='SocialApp_l_user_id_b67f88_idx'),
        ),
        migrations.AddIndex(
            model_name='likeimagerelation',
            index=models.Index(fields=['image'], name='SocialApp_l_image_i_a8fd35_idx'),
        ),
    ]
