# Generated by Django 4.1 on 2023-04-18 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImagesApp', '0014_delete_aronaimagecounter_alter_aronaimage_uploader'),
        ('UsersApp', '0004_followrelation_remove_user_followers'),
        ('SocialApp', '0006_remove_likecommentrelation_socialapp_l_usernam_1957b7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='belong_to_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImagesApp.aronaimage'),
        ),
        migrations.AlterField(
            model_name='likecommentrelation',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialApp.comment'),
        ),
        migrations.AlterField(
            model_name='likecommentrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.user'),
        ),
        migrations.AlterField(
            model_name='likeimagerelation',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImagesApp.aronaimage'),
        ),
        migrations.AlterField(
            model_name='likeimagerelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.user'),
        ),
    ]
