# Generated by Django 4.1 on 2023-04-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0007_alter_comment_belong_to_image_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='SocialApp_c_belong__1223de_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='SocialApp_c_belong__95f1ab_idx',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['belong_to_image'], name='SocialApp_c_belong__1223de_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['belong_to_comment'], name='SocialApp_c_belong__95f1ab_idx'),
        ),
    ]
