# Generated by Django 4.1 on 2023-04-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0008_remove_comment_socialapp_c_belong__1223de_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply_to_user',
            new_name='reply_to_user_username',
        ),
    ]
