# Generated by Django 4.1 on 2023-04-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0009_rename_reply_to_user_comment_reply_to_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecommentrelation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='likeimagerelation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
