# Generated by Django 4.1 on 2023-05-14 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0010_alter_likecommentrelation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply_to_comment_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to_comment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_reply_to_comment', to='SocialApp.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='belong_to_comment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_belong_to_comment', to='SocialApp.comment'),
        ),
    ]
