# Generated by Django 4.1 on 2023-05-20 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImagesApp', '0022_alter_aronaimage_uploader_and_more'),
        ('SocialApp', '0011_remove_comment_reply_to_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='belong_to_comment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belonging_comments', to='SocialApp.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='belong_to_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_comments', to='ImagesApp.aronaimage'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_to_comment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replying_comments', to='SocialApp.comment'),
        ),
        migrations.AlterField(
            model_name='likecommentrelation',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='SocialApp.comment'),
        ),
        migrations.AlterField(
            model_name='likeimagerelation',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_likes', to='ImagesApp.aronaimage'),
        ),
    ]
